tinymce.addI18n('uk',{
"Shortcodes": "Шорткоди",
"Structure": "Структура",
"Components": "Компоненти",
"Active Components": "Активні компоненти",
"Grid": "Розмітка",
"Custom Grid": "Власна розмітка",
"Number of columns": "Кількість стовпців",
"Button": "Кнопка",
"Insert button": "Вставити кнопку",
"Button text...": "Текст кнопки...",
"Type": "Тип",
"Default": "За замовчуванням",
"Primary": "Основний",
"Success": "Успіх",
"Info": "Інформація",
"Warning": "Попередження",
"Danger": "Небезпека",
"Link": "Посилання",
"Size": "Розмір",
"Large": "Великий",
"Small": "Маленький",
"Extra small": "Дуже маленький",
"Icon": "Іконка",
"Insert icon": "Вставити іконку",
"Icon name": "Назва іконки",
"Alert": "Попередження",
"Insert alert": "Вставити попередження",
"Label": "Позначка",
"Insert label": "Вставити позначку",
"Lead": "Виділення",
"Insert lead": "Вставити виділення",
"Progress Bar": "Індикатор виконання",
"Insert progress bar": "Вставити індикатор виконання",
"Percentage": "Відсоток виконання",
"Well": "Комірка",
"Insert well": "Вставити комірку",
"Panel": "Панель",
"Insert panel": "Вставити панель",
"Content": "Вміст",
"Call to Action": "Заклик до дії",
"Insert call to action": "Вставити заклик до дії",
"Widget": "Віджет",
"Tabs": "Вкладки",
"Collapse": "",
"Accordion": "Акордеон",
"Tooltip": "Підказка",
"Map": "Карта",
"Info window": "Інфо вікно",
"Latitude": "Широта",
"Longtitude": "Довгота",
"Zoom": "Зум",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": ""

});